---
- name: Test custom collection module
  hosts: all
  strategy: free

  tasks:
  - name: make Volume Group
    community.general.lvg:
     vg: "VGtest"
     pvs: /dev/sdb
     state: present

  - name: make Logical volume
    community.general.lvol:
      vg: VGtest
      lv: LVtest1
      size: 2g
      resize: true

  - name: Create filesystem
    community.general.filesystem:
      fstype: xfs
      dev: /dev/VGtest/LVtest1
      state: present
  
  - name: Make dirs
    ansible.builtin.file:
      path: /lv_test1
      state: directory

  - name: Mount device
    ansible.posix.mount:
      path: /lv_test1
      fstype: xfs
      src: /dev/mapper/VGtest-LVtest1



